name: example
description: A sample command-line application.
version: 1.1.0
publish_to: none

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  censor_it:
    path: ../

dev_dependencies:
  lints: ^4.0.0
