name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
    censor_it: 
      git:
        url: https://github.com/pavluke/censor_it.git

dev_dependencies:
  lints: ^4.0.0
