name: censor_it
description: A Dart library for censoring text based on predefined patterns and
  customizable characters.
version: 2.1.2
repository: https://github.com/pavluke/censor_it
homepage: https://github.com/pavluke/censor_it
issue_tracker: https://github.com/pavluke/censor_it/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  meta: ^1.18.3

dev_dependencies:
  pavluke_lints: ^1.2.1
  test: ^1.31.0

topics:
  - censorship
  - profanity-filter
  - text-processing
  - multilingual
  - dart-library

screenshots:
  - description: "CensorIt Logo"
    path: images/logo.png
  - description: "CensorIt Banner"
    path: images/banner.png
