part of '../censor_pattern_enum.dart';

final RegExp _itRegExp = RegExp(
    r'(?<![a-zàèéìòù])'
    r'(?:'
    r'vaffanculo' // vaffanculo
    r'|cazz[a-zàèéìòù]*' // cazzo, cazzata, cazzoni ...
    r'|coglion[a-zàèéìòù]*' // coglione, coglioni ...
    r'|stronz[a-zàèéìòù]*' // stronzo, stronzi ...
    r'|troi[a-zàèéìòù]*' // troia, troie ...
    r'|puttan[a-zàèéìòù]*' // puttana, puttane ...
    r'|merd[a-zàèéìòù]*' // merda, merdoso ...
    r')'
    r'(?![a-zàèéìòù])',
    caseSensitive: false);
