part of '../censor_pattern_enum.dart';

final RegExp _plRegExp = RegExp(
  r'(?<![a-ząćęłńóśźż])'
  r'(?:'
  r'kurw[a-ząćęłńóśźż]*' // kurwa, kurwy, kurwie, kurwo...
  r'|skurw[a-ząćęłńóśźż]*' // skurwiel, skurwysyn, skurwiony...
  r'|chuj[a-ząćęłńóśźż]*' // chuj, chuja, chujem, chuje...
  r'|jeb[a-ząćęłńóśźż]*' // jebać, jebany, jebana, jebane...
  r'|pierdol[a-ząćęłńóśźż]*' // pierdolę, pierdolić, pierdolony...
  r'|pizd[a-ząćęłńóśźż]*' // pizda, pizdy, pizdę, pizdo...
  r')'
  r'(?![a-ząćęłńóśźż])',
  caseSensitive: false,
  unicode: true,
);
