part of '../censor_pattern_enum.dart';

final RegExp _ptRegExp = RegExp(
  r'(?<![a-záàâãçéêíóôõúü])'
  r'(?:'
  r'filhos?\s*da\s*puta' // filho da puta / filhos da puta
  r'|caralh[a-záàâãçéêíóôõúü]*' // caralho, caralhada...
  r'|fod[a-záàâãçéêíóôõúü-]*' // foda, foder, fodido, foda-se...
  r'|porr[a-záàâãçéêíóôõúü]*' // porra, porrão, porrada (вулг.) ...
  r'|puta[a-záàâãçéêíóôõúü]*' // puta, putaria...
  r'|merd[a-záàâãçéêíóôõúü]*' // merda, merdas...
  r'|cu(?:z[aã]o|zon[aã])?[a-záàâãçéêíóôõúü]*' // cu, cuzão, cuzona...
  r')'
  r'(?![a-záàâãçéêíóôõúü])',
  caseSensitive: false,
  unicode: true,
);
